name: CI-Test-2
on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]
  workflow_dispatch: 
  
env:

  CI: true



jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: test step 1
        run: sleep 40
